### ISSUE TITLE
Identifier 'i' has already been declared

### ISSUE THREAD

**Issue by nixkewllikem3** [RileyXX/WalgreensAutoCouponClipper#2]
Uncaught SyntaxError: Identifier 'i' has already been declared
    at <anonymous>:3:81

**Comment by wiltsw** [comment]
Fixed by wiltsw:patch-1

**Comment by RileyXX** [comment]
Approved https://github.com/RileyXX/WalgreensAutoCouponClipper/pull/3

**Comment by RileyXX** [comment]
Thank you very much for reporting this
